# Snake Contribution Configuration
# This file configures automated snake contribution generation

# GitHub Configuration
github:
  # GitHub username to generate contributions for (required)
  username: "currentsuspect"
  
  # GitHub token (for private repositories, optional but recommended)
  # Generate at: https://github.com/settings/tokens
  token: "${GITHUB_TOKEN}"  # Using GitHub's default token
  
  # Repository where to commit the generated files
  repository: "${GITHUB_REPOSITORY}"  # Uses current repository

# Output Configuration
outputs:
  # Define multiple output files with different configurations
  - path: "github-snake.svg"
    type: "svg"
    palette: "github"
    description: "Standard light theme snake SVG"
    
  - path: "github-snake-dark.svg"
    type: "svg"
    palette: "github-dark"
    description: "Dark theme snake SVG for dark mode support"
    
  - path: "snake.gif"
    type: "gif"
    palette: "github"
    color_snake: "orange"
    color_dots: "#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9"
    description: "Animated GIF with custom ocean colors"

# Automation Configuration
automation:
  # Enable/disable automatic generation
  enabled: true
  
  # Schedule for generation (CRON format)
  # Examples:
  # - "0 0 * * *" (daily at midnight)
  # - "0 0 1 * *" (monthly on the 1st)
  # - "0 0 1,15 * *" (twice monthly on 1st and 15th)
  schedule: "0 0 1,15 * *"
  
  # Branch to commit changes to
  commit_branch: "main"
  
  # Commit message template
  commit_message: "Update snake contributions on ${DATE}"
  
  # Enable/disable committing changes
  auto_commit: true

# GitHub Profile README Integration
readme_integration:
  # Whether to update README.md with snake contribution
  enabled: true
  
  # README.md path (relative to repository root)
  readme_path: "README.md"
  
  # Snake image tag to insert
  # Options: "svg", "picture"
  tag_type: "picture"
  
  # Position to insert the tag ("top", "bottom", or line number)
  position: "top"

# Advanced Configuration
advanced:
  # Custom snake path algorithm (if supported)
  algorithm: "default"
  
  # Frame rate for GIF generation (frames per second)
  frame_rate: 10
  
  # Animation speed multiplier
  animation_speed: 1.0
  
  # Generate debug information
  debug: false
  
  # Cache duration (to avoid excessive API calls)
  cache_hours: 24

# Notification Configuration
notifications:
  # Enable/disable notifications
  enabled: true
  
  # Discord webhook URL (if you want Discord notifications)
  discord_webhook: ""
  
  # Slack webhook URL (if you want Slack notifications)
  slack_webhook: ""