name: Generate Snake Contributions

permissions:
  contents: write

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]
  schedule:
    - cron: "0 0 1,15 * *"

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate snake contribution graphics
        uses: Platane/snk@v3
        with:
          github_user_name: currentsuspect
          outputs: |
            dist/github-snake.svg?palette=github
            dist/github-snake-dark.svg?palette=github-dark
            dist/snake.svg?palette=github&color_snake=#8B7FFF&color_snake_opacity=0.8&color_bg=transparent

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dist/
          git diff --staged --quiet || git commit -m "Update snake contributions on $(date)"
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/currentsuspect/currentsuspect.git
